const $=id=>document.getElementById(id),C=window.WordCore,V=window.WordVocabulary;
const libraries=V.createRegistry();let catalogReady=null,activeLibrary=null;
function ensureCatalog(){return catalogReady||(catalogReady=libraries.loadManifest('data/catalog.json').catch(e=>{catalogReady=null;throw e}))}
let words=[],queue=[],answers=[],index=0,hints=0,graded=false,mode='full',scope='',currentSense='',isDemo=false,active=false,loadVersion=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){for(const x of ['setup','quiz','results'])$(x).hidden=x!==id;window.scrollTo(0,0)}
function selection(){try{const r=C.range($('range').value,words.map(w=>w.list)),available=new Set(words.map(w=>w.list)),missing=r.filter(n=>!available.has(n));if(missing.length)throw Error('词表中没有 List '+missing.join('、')+'，请调整范围或导入完整词表。');return words.filter(w=>r.includes(w.list))}catch(e){throw e}}
const listCounts=new Map();
function listPlan(){return C.range($('range').value,words.map(w=>w.list)).map(list=>({list,count:listCounts.get(list)===''?NaN:Number(listCounts.get(list))}))}
function renderListCounts(){let lists=[];try{lists=C.range($('range').value,words.map(w=>w.list))}catch{}$('listCounts').innerHTML=lists.map(list=>{const available=words.filter(w=>w.list===list).length;if(!listCounts.has(list))listCounts.set(list,String(Math.min(10,available)));return `<div class="count-row"><label for="list-count-${list}">List ${list}<small>共 ${available} 个词</small></label><input id="list-count-${list}" data-count-list="${list}" type="number" min="0" max="${available}" step="1" value="${esc(listCounts.get(list))}" aria-label="List ${list} 抽取数量"><span>个</span></div>`}).join('')}
function updateSelection(){const perList=$('sampling').value==='per-list';$('perListSettings').hidden=!perList;$('totalSettings').hidden=perList;try{let selected=selection(),total=perList?0:C.totalCount($('count').value,selected.length);$('count').max=selected.length;if(perList){const plan=listPlan();total=0;for(const row of plan){const available=selected.filter(w=>w.list===row.list).length;if(!Number.isInteger(row.count)||row.count<0)throw Error('List '+row.list+' 的抽取数量需为 0 或正整数。');if(row.count>available)throw Error('List '+row.list+' 只有 '+available+' 个词，请减少抽取数量。');total+=row.count}if(!total)throw Error('请至少抽取 1 个单词。')}$('selection').textContent=`已选 ${selected.length} 个词 · 本轮 ${total} 题`;$('setupError').textContent='';$('start').disabled=!selected.length}catch(e){$('selection').textContent='';$('setupError').textContent=e.message;$('start').disabled=true}let r=[];try{r=C.range($('range').value,words.map(w=>w.list))}catch{}document.querySelectorAll('.chip').forEach(el=>el.classList.toggle('selected',r.includes(+el.dataset.list)))}
function renderPreview(){let lists=[...new Set(words.map(w=>w.list))].sort((a,b)=>a-b);$('wordCount').textContent=words.length+' 个词';$('lists').innerHTML=lists.map(l=>`<span class="chip" data-list="${l}">List ${l} <strong>${words.filter(w=>w.list===l).length}</strong></span>`).join('');$('preview').innerHTML=words.map(w=>`<tr><td><strong>${esc(w.word)}</strong><small>${esc(w.phonetic||'未提供音标')}</small></td><td><span class="word-pos">${esc(w.pos)}</span>${esc(w.senses.join('；'))}</td><td><span class="pill">${w.list}</span></td></tr>`).join('');renderListCounts();updateSelection()}
$('range').addEventListener('input',()=>{renderListCounts();updateSelection()});$('count').addEventListener('input',updateSelection);$('sampling').addEventListener('change',updateSelection);$('listCounts').addEventListener('input',e=>{if(e.target.dataset.countList){listCounts.set(+e.target.dataset.countList,e.target.value);updateSelection()}});
function useWordList(text,name,isDefault=false,encoding='UTF-8'){
 const parsed=C.parse(text);if(!parsed.words.length)throw Error('没有识别到词条，请检查词表格式。');
 return useLibrary(V.fromLegacy(parsed,{name}),isDefault,encoding);
}
function useLibrary(library,isDefault=false,encoding='UTF-8'){
 const nextWords=V.toPracticeWords(library);if(!nextWords.length)throw Error('没有识别到词条，请检查词表格式。');
 const name=library.name,parsed={warnings:library.importDiagnostics||[]};
 activeLibrary=library;words=nextWords;listCounts.clear();const lists=[...new Set(words.map(w=>w.list))].sort((a,b)=>a-b);
 if(!isDefault)$('range').value=lists.join(',');else{try{C.range($('range').value,lists)}catch{$('range').value=String(lists[0])}}
 $('sourceBadge').textContent=name;$('defaultNotice').hidden=!isDefault;$('restoreDefault').hidden=isDefault;$('loadError').hidden=true;
 $('importNotice').className='';$('importNotice').innerHTML=`<p class="small">${isDefault?'默认词库已就绪':'已临时导入'} · ${words.length.toLocaleString()} 个词条 · ${lists.length} 个 List${isDefault?'':' · '+encoding}</p>`;
 const noIPA=words.filter(w=>!w.phonetic).length;
 if(parsed.warnings.length||noIPA){const d=document.createElement('details');d.className='source-notes';d.innerHTML=`<summary>词表核对说明${parsed.warnings.length?' · '+parsed.warnings.length+' 处格式或重复记录':''}</summary>${parsed.warnings.length?'<pre>'+parsed.warnings.map(w=>'第 '+w.line+' 行 · '+esc(w.reason)+'\n'+esc(w.text)).join('\n\n')+'</pre>':''}${noIPA?'<p class="small">'+noIPA+' 个词条原文未提供音标，以短语为主；检查时显示释义。</p>':''}`;$('importNotice').append(d)}
 renderPreview();
}
async function loadLibrary(libraryId){if(active)throw Error('请先结束当前检查。');const version=++loadVersion;$('sourceBadge').textContent='正在加载默认词库…';$('start').disabled=true;$('loadError').hidden=true;
 try{await ensureCatalog();const library=await libraries.load(libraryId||libraries.defaultId);if(version!==loadVersion)return;useLibrary(library,library.id===libraries.defaultId);return library.id}catch(e){if(version!==loadVersion)return;$('sourceBadge').textContent=words.length?'保留当前词表':'默认词库未加载';$('loadError').hidden=false;if(words.length)updateSelection()}
}
function loadDefault(){return loadLibrary()}
// Lightweight integration/test entry point; no new selector or persistence UI.
window.WordCheckLibraries={register:entry=>libraries.register(entry),switchLibrary:loadLibrary,list:()=>libraries.list().map(({id,version})=>({id,version})),get activeId(){return activeLibrary?.id||null}};
$('retryLoad').onclick=loadDefault;$('restoreDefault').onclick=loadDefault;
$('file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const version=++loadVersion;try{if(file.size>2*1024*1024)throw Error('文件超过 2 MB，请先精简词表。');const buf=await file.arrayBuffer();let text,encoding='UTF-8';try{text=new TextDecoder('utf-8',{fatal:true}).decode(buf)}catch{text=new TextDecoder('gb18030',{fatal:true}).decode(buf);encoding='GB18030'}if(version!==loadVersion)return;useWordList(text,file.name,false,encoding)}catch(err){$('importNotice').textContent=err.message;$('importNotice').className='error';updateSelection()}finally{e.target.value=''}});
function begin(pool,chosenMode,chosenScope){if(!pool.length)throw Error('没有可用词条。');queue=C.shuffle(pool);answers=[];index=0;mode=chosenMode;scope=chosenScope;active=true;show('quiz');renderQuestion();return{questions:queue.length,mode,scope}}
$('start').onclick=()=>{try{const selected=selection(),perList=$('sampling').value==='per-list',plan=perList?listPlan():null,count=$('count').value;let pool=perList?C.sampleByList(selected,plan):C.sampleMixed(selected,count);const label=perList?plan.filter(p=>p.count>0).map(p=>`List ${p.list} 抽 ${p.count} 个`).join(' · '):'List '+$('range').value;begin(pool,document.querySelector('[name=mode]:checked').value,label)}catch(e){$('setupError').textContent=e.message}};
function renderQuestion(){const w=queue[index];hints=0;graded=false;currentSense=w.senses[Math.floor(Math.random()*w.senses.length)];$('quizMode').textContent=mode==='full'?'音标 + 释义':'单个释义';$('progressText').textContent=`${index+1} / ${queue.length}`;$('progressBar').style.width=`${index/queue.length*100}%`;$('questionList').textContent=`LIST ${String(w.list).padStart(2,'0')}`;$('phonetic').hidden=mode==='single';$('phonetic').textContent=w.phonetic||'未提供音标';$('meaning').textContent=mode==='single'?currentSense:w.senses.join('；');$('pos').textContent=mode==='full'?w.pos:'';$('pos').hidden=mode==='single';$('answer').value='';$('answer').disabled=false;$('hintDisplay').textContent='';$('feedback').textContent='';$('feedback').className='';$('hint').disabled=false;$('submit').hidden=false;$('skip').hidden=false;$('next').hidden=true;$('answer').focus()}
$('hint').onclick=()=>{if(graded)return;const w=queue[index];hints++;let letters=0;$('hintDisplay').textContent=Array.from(w.word).map(c=>/[A-Za-z]/.test(c)?(++letters<=hints?c:'_'):c).join(' ');$('hint').disabled=hints>=w.word.replace(/[^a-z]/gi,'').length;$('answer').focus()};
function grade(skip=false){if(graded||!active)return;let typed=$('answer').value.trim();if(!typed&&!skip){$('answer').setCustomValidity('请先输入答案，或选择“不会，查看答案”。');$('answer').reportValidity();return}$('answer').setCustomValidity('');let w=queue[index],ok=!skip&&C.accepts(w,typed),status=ok?(hints?'assisted':'correct'):'wrong';answers.push({entry:w,typed,hints,status,prompt:mode==='single'?currentSense:w.senses.join('；')});graded=true;$('answer').disabled=true;$('hint').disabled=true;$('submit').hidden=true;$('skip').hidden=true;$('feedback').className='feedback '+status;$('feedback').innerHTML=`<strong>${ok?(hints?'提示后答对':'独立答对，记得很牢！'):(skip?'这个词再练一次':'拼写还差一点')}</strong><br>正确答案：<strong>${esc(w.word)}</strong>${!ok?'<br>'+esc(w.senses.join('；')):''}`;if(!ok&&mode==='single')$('feedback').insertAdjacentHTML('beforeend','<br><small>按词表原词判分；若写出其他同义词，可由老师另行判断。</small>');$('next').textContent=index===queue.length-1?'查看本轮结果':'下一题';$('next').hidden=false;$('next').focus()}
$('answer').oninput=()=>$('answer').setCustomValidity('');$('answerForm').onsubmit=e=>{e.preventDefault();grade()};$('skip').onclick=()=>grade(true);$('next').onclick=()=>{if(!graded)return;if(++index>=queue.length)finish();else renderQuestion()};
$('exit').onclick=()=>{if(window.confirm('结束本轮并查看已完成题目的结果？'))finish()};
function finish(){active=false;show('results');$('resultTitle').textContent=answers.length===queue.length?'本轮检查完成':'本轮已结束';$('resultScope').textContent=`${isDemo?'示例词表 · ':''}${scope} · ${mode==='full'?'音标 + 释义':'单个释义'} · 已完成 ${answers.length} / ${queue.length} 题`;$('independent').textContent=answers.filter(a=>a.status==='correct').length;$('assisted').textContent=answers.filter(a=>a.status==='assisted').length;$('incorrect').textContent=answers.filter(a=>a.status==='wrong').length;$('review').innerHTML=answers.map(a=>`<tr><td><strong>${esc(a.entry.word)}</strong><small>List ${a.entry.list}</small></td><td class="review-answer">${esc(a.typed||'未作答')}</td><td><span class="pill ${a.status}">${{correct:'独立答对',assisted:'提示后答对',wrong:'待复习'}[a.status]}</span>${a.hints?'<small>提示 '+a.hints+' 个字母</small>':''}</td><td>${esc(a.entry.senses.join('；'))}</td></tr>`).join('')||'<tr><td colspan="4">本轮尚未完成任何题目。</td></tr>';$('retry').disabled=!answers.some(a=>a.status!=='correct')}
$('restart').onclick=()=>{show('setup');updateSelection()};$('retry').onclick=()=>begin(answers.filter(a=>a.status!=='correct').map(a=>a.entry),mode,scope+' · 巩固练习');
window.addEventListener('beforeunload',e=>{if(active){e.preventDefault();e.returnValue=''}});
loadDefault();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_vocabulary_summary',description:'Read the loaded vocabulary lists and the current quiz status without revealing answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return{lists:[...new Set(words.map(w=>w.list))],words:words.length,isDemo,active,completed:answers.length}}},{name:'start_vocabulary_check',description:'Start a new vocabulary check from the loaded lists. Fails while a quiz is active.',inputSchema:{type:'object',properties:{lists:{type:'string'},mode:{type:'string',enum:['full','single']},count:{type:'integer',minimum:0,maximum:10000}},required:['lists','mode','count'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(active)throw Error('请先结束当前检查。');if(!input||typeof input.lists!=='string'||!['full','single'].includes(input.mode)||!Number.isInteger(input.count)||input.count<0||input.count>10000)throw Error('Invalid quiz settings');const r=C.range(input.lists,words.map(w=>w.list));if(r.some(n=>!words.some(w=>w.list===n)))throw Error('所选 List 不在词表中。');let pool=C.sampleMixed(words.filter(w=>r.includes(w.list)),input.count);return begin(pool,input.mode,'List '+input.lists)}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
